[tool.poetry]
name = "supply"
version = "0.1.0"
description = "Supply Chain Streamlit App"
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
streamlit = "^1.40.0"
faker = "^25.0.0"
pandas = "^2.2.0"
numpy = "^2.1.0"
scikit-learn = "^1.5.0"
matplotlib = "^3.9.0"
