[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
python = "^3.13"
streamlit = "^1.40.0"
faker = "^25.0.0"
pandas = "^2.2.0"
numpy = "^2.1.0"
scikit-learn = "^1.5.0"
matplotlib = "^3.9.0"

